# Generated by Django 4.0.1 on 2024-06-06 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0004_etudiant'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='niveau',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='promo.niveau'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etudiant',
            name='promo',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='promo.promo'),
            preserve_default=False,
        ),
    ]
