# Generated by Django 4.0.1 on 2024-06-06 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0007_etudiant_cohorte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='niveau',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='promo.niveau'),
        ),
    ]
