# Generated by Django 4.0.1 on 2024-06-06 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0008_alter_etudiant_niveau'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='cohorte',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='promo.cohorte'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='promo',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='promo.promo'),
        ),
    ]
