# Generated by Django 4.0.1 on 2024-06-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0011_module_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='assistants',
            field=models.ManyToManyField(to='promo.Assistant'),
        ),
    ]
